### PR TITLE
Add Graph in Dashboard

### PR DESCRIPTION
**Pull request by binayshaw7777**
#229

### CODE REVIEW

**Comment by maityamit** [comment]
@binayshaw7777 Please tag here the issue number on comment section

**Comment by binayshaw7777** [comment]
> @binayshaw7777 Please tag here the issue number on comment section

Done

**Comment by maityamit** [comment]
> > @binayshaw7777 Please tag here the issue number on comment section
> 
> Done

Tag Like #XX where XX means the issue no

**Comment by binayshaw7777** [comment]
> > > @binayshaw7777 Please tag here the issue number on comment section
> > 
> > 
> > Done
> 
> Tag Like #XX where XX means the issue no

Okok

**Pull request merged**
