### PR TITLE
adding alert dialog for confirming logout

### PR DESCRIPTION
**Pull request by afreenabegum**
Adding alert window to make sure that user wants to logout or not.

### CODE REVIEW

**Comment by maityamit** [comment]
@afreenabegum 
I see your changes , but is is used Java and this is an Android Application . 
You must be used android Java and Android Studio stacks . You are using web dev components . 
Please Refer this two links: 
and do this type of alert dialog box  :

Stackoverflow : https://stackoverflow.com/questions/2115758/how-do-i-display-an-alert-dialog-on-android
Google : https://developer.android.com/guide/topics/ui/dialogs

Hope you understand.

**Comment by afreenabegum** [comment]
> @afreenabegum I see your changes , but is is used Java and this is an Android Application . You must be used android Java and Android Studio stacks . You are using web dev components . Please Refer this two links: and do this type of alert dialog box :
> 
> Stackoverflow : https://stackoverflow.com/questions/2115758/how-do-i-display-an-alert-dialog-on-android Google : https://developer.android.com/guide/topics/ui/dialogs
> 
> Hope you understand.

Sure I'll be making changes.
thank you.

**Comment by maityamit** [comment]
Yes , @afreenabegum This commits is ok , but there is some silly mistake . I will definitely say , I will merge your PR after 1st Feb , When the Coding round will began of JWOC . 

And please mention as yourself in the jwoc discord server in my threads ( Project -> Tracky ) 
That I will track your identity and mark you.

**Comment by afreenabegum** [comment]
Thank you @maityamit .Actually I am not aware of android dev ,am familiar with web-development. This is the reason I mad some mistakes. Somehow, I did it : )
Thanks for helping me out.

**Comment by maityamit** [comment]
@afreenabegum 
As per jwoc coding round begin from 1.02.22
So you can now create a new PR. This PR I dismissed. 

Thanks

**Comment by afreenabegum** [comment]
@maityamit should I make changes again?

**Comment by maityamit** [comment]
@afreenabegum 
You can just create a new PR .

**Comment by afreenabegum** [comment]
Hey @maityamit .Can you please help me with how to create new PR for already existing file. little confused

**Comment by maityamit** [comment]
@afreenabegum 
Say  , but your previous pr was also mistake means , it is not right code . There is some error . 

So , Now you can check that Error , and solve properly. Then you can send me the snap into the discord group of that changes portion , after that , you will create a new PR. 

You can take help from : https://stackoverflow.com/questions/2478517/how-to-display-a-yes-no-dialog-box-on-android

**Comment by afreenabegum** [comment]
> @afreenabegum Say , but your previous pr was also mistake means , it is not right code . There is some error .
> 
> So , Now you can check that Error , and solve properly. Then you can send me the snap into the discord group of that changes portion , after that , you will create a new PR.
> 
> You can take help from : https://stackoverflow.com/questions/2478517/how-to-display-a-yes-no-dialog-box-on-android

okay. I'll make changes.

**Pull request closed without merging**
